### PR TITLE
Replaced lodash with core-util-is

### PR DESCRIPTION
**Pull request by trygve-lie**
Ref discussion in: https://github.com/helmetjs/helmet/issues/95

Slims down the size of helmet quite a lot. Tests pass on latest node.js 0.10.x, 0.12.x and iojs 1.8.x.

### CODE REVIEW

**Comment by EvanHahn** [comment]
I'll merge once Travis says it's okay. Thanks!

**Comment by EvanHahn** [comment]
Merged! This will be deployed to npm soon.

**Comment by trygve-lie** [comment]
\o/

**Comment by EvanHahn** [comment]
I'm building a list of contributors for a new Helmet.js website. Do you have a name and/or website you want me to use to credit you?

**Pull request merged**
