### PR TITLE
Change API to accept seconds instead of milliseconds.

### PR DESCRIPTION
**Pull request by frodsan**

### CODE REVIEW

**Comment by frodsan** [comment]
I think the default max age must be increased too. 1 day is not a good default. Rails uses 180 days, which is the low end for SSLLabs and greater than the 18 week required for preload list.

Also, the setIf example could be improved with a more real use case, for example, using this library in a proxy-setup (like heroku):

```js
  hsts: {
      // ...
      setIf: (req) => req.secure || (req.headers["x-forwarded-proto"] === "https"),
    },
```

**Comment by frodsan** [comment]
Also, `includeSubDomains` is added by default. See https://github.com/rails/rails/pull/22663

**Comment by frodsan** [comment]
I also found in the code that you can't pass `0` as `maxAge`, but that's actually a valid value. That's the way you can disable HSTS immediately. If you don't want to use `0`, maybe you can use `false` to disable hsts (using maxAge `0`).

**Comment by frodsan** [comment]
I've been reading #5 

> If we pick a default maxAge that is too long, this middleware can mess up somebody's website if they've screwed up their HTTPS somehow.

In that case, I would disable hsts using `maxAge=0`.

**Comment by EvanHahn** [comment]
Sorry to be so slow on this—I've been busy!

Just merged this into the `2.0` branch. I'm closing this and you can check out the [2.0 PR](https://github.com/helmetjs/hsts/pull/11) for more.

It sounds like there are a number of things this module needs to address. I've added issues for each of these things:

- API should accept _seconds_, not milliseconds (this PR and issue #7)
- `includeSubdomains` should be `true` by default (#10)
- default `maxAge` is too short (#5)

I agree with all of these things and we'll do them in `hsts@2`.

As far as disabling HSTS: I believe you _can_ set the `maxAge` to 0, and there are even tests for it. Perhaps I'm missing something? If there _is_ a problem with this, could you open a new issue?

Thanks for your contribution! If you'd like to add yourself to `contributors` in `package.json`, feel free to add another PR.

**Comment by EvanHahn** [comment]
@frodsan I'm planning on starting a list of contributors (a big list of bullet points) and I'd like to put you on there. How should I credit you?

**Pull request closed without merging**
